### ISSUE TITLE
Error loop on wrong username/password

### ISSUE THREAD

**Issue by p0358** [concierge/facebook#1]
```
info login Logging in...
ERR! login Wrong username/password.
2017-05-24T16:19:41.202Z - error:  error=Wrong username/password.
2017-05-24T16:19:41.204Z - error: "kpm_facebook" wywalił się. <unknown> jest teraz pokryty chorobą.
2017-05-24T16:19:41.205Z - error: Error: [object Object]
    at /var/www/Concierge/modules/kpm_facebook/facebook.js:132:27
    at /var/www/Concierge/modules/kpm_facebook/node_modules/facebook-chat-api/index.js:424:7
    at tryCatcher (/var/www/Concierge/modules/kpm_facebook/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/var/www/Concierge/modules/kpm_facebook/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/var/www/Concierge/modules/kpm_facebook/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/var/www/Concierge/modules/kpm_facebook/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/var/www/Concierge/modules/kpm_facebook/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/var/www/Concierge/modules/kpm_facebook/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/var/www/Concierge/modules/kpm_facebook/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

2017-05-24T16:19:41.206Z - error: Facebook has crashed, reloading...
2017-05-24T16:19:41.207Z - info: Wyładowywanie modułu "facebook".
2017-05-24T16:19:41.207Z - debug: Integration "facebook" failed to stop.
2017-05-24T16:19:41.208Z - error: TypeError: Cannot read property '_stopTyping' of null
    at FacebookIntegration.stop (/var/www/Concierge/modules/kpm_facebook/facebook.js:204:33)
    at ModuleLoader.stopIntegration (/var/www/Concierge/core/modules/modules.js:397:29)
    at ModuleLoader.unloadModule (/var/www/Concierge/core/modules/modules.js:315:26)
    at Platform.onError (/var/www/Concierge/modules/kpm_auto_restart/auto_restart.js:10:16)
    at emitMany (events.js:132:20)
    at Platform.emit (events.js:201:7)
    at /var/www/Concierge/core/common/middleware.js:29:29
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

2017-05-24T16:19:41.269Z - info: Ładowanie modułu 'facebook'...
2017-05-24T16:19:41.275Z - info: Ładowanie zakończono pomyślnie
info login Logging in...
ERR! login Wrong username/password. [...]
```

**Comment by drkno** [comment]
This is because you have auto_restart installed. If you have the latest facebook integration and lastest `facebook-chat-api` npm package then `auto_restart` is no longer needed (and you won't have this issue).
